version: '3.9'

services:
  db:
      image: postgres:13.0-alpine
      volumes:
       - postgres_data:/var/lib/postgresql/data/
      env_file:
       - ./config/dev.env.db
      
      ports:
          - "5432:5432"
  web:
    build: .
    command: python3 manage.py runserver
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env

  celery:
    build: .
    command: celery -A trafficlight worker --loglevel=info
    volumes:
      - .:/app

    env_file:
      - .env

  celery-beat:
    build: .
    command: celery -A trafficlight beat --loglevel=info
    volumes:
      - .:/app
   
    env_file:
      - .env


